name: Outputs Sample
on: workflow_dispatch

jobs:
  set-outputs:
    runs-on: ubuntu-latest
    outputs:
      my-outputs: ${{ steps.set.outputs.my-outputs }};
      my-outputs2: ${{ steps.set.outputs.my-outputs2 }};
      some-outputs: ${{ steps.out.outputs.some-outputs }};
    steps:
      - name: Create Outputs
        id: set
        run: |
          echo "my-outputs=初めてのoutputs" >> $GITHUB_OUTPUT
          echo "my-outputs2=こんちゃ" >> $GITHUB_OUTPUT
      - name: Create Outputs2
        id: out
        run: echo "some-outputs=初めてのoutputs2" >> $GITHUB_OUTPUT

  load-outputs:
    runs-on: ubuntu-latest
    needs: set-outputs
    steps:
      - name: Read Outputs
        run: |
          echo "my-outputs: ${{ needs.set-outputs.outputs.my-outputs }}"
          echo "some-outputs: ${{ needs.set-outputs.outputs.some-outputs }}"
