name: Outputs Sample
on: workflow_dispatch

jobs:
  set-outputs:
    runs-on: ubuntu-latest
    outputs:
      my-outputs: ${{ steps.set.outputs.my-outputs }};
    steps:
      - name: Create Outputs
        id: set
        run: echo "my-outputs=初めてのoutputs" >> $GITHUB_OUTPUT

  load-outputs:
    runs-on: ubuntu-latest
    needs: set-outputs
    steps:
      - name: Read Outputs
        run: |
          echo "my-outputs: ${{ needs.set-outputs.outputs.my-outputs }}"
